version: '3.3'

services:
  usermsa:
    container_name: usermsa
    hostname: usermsa
    image: usermsa
    restart: on-failure
    build: .
    ports:
      - 80:8080
      - 443:8443
    expose:
      - '8080'
      - '8443'
    networks:
      - backend
networks:
  backend:
    driver: bridge